# Generated by Django 4.1 on 2022-09-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='thumb',
            field=models.FileField(upload_to='media/'),
        ),
    ]
