# Generated by Django 4.1.4 on 2023-10-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_alter_uploadfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='thumb',
            field=models.FileField(upload_to='media/'),
        ),
    ]
