# Generated by Django 4.1.4 on 2023-10-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_alter_uploadfile_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='size',
            field=models.TextField(default='', max_length=10),
        ),
    ]
