# Generated by Django 4.1.4 on 2023-10-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0006_uploadfile_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='size',
            field=models.CharField(default='', max_length=10),
        ),
    ]
