# Generated by Django 4.1.4 on 2023-10-31 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0007_alter_uploadfile_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
