# Generated by Django 4.1.4 on 2023-11-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0008_uploadfile_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='thumb',
            field=models.FileField(upload_to='tumb'),
        ),
    ]
