# Generated by Django 4.1.4 on 2023-11-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0009_alter_uploadfile_file_alter_uploadfile_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='thumb',
            field=models.ImageField(upload_to='tumb'),
        ),
    ]
